name: 🚀 Deploy (Production)

env:
  AZURE_WEBAPP_NAME: iot-express-api

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 🔽 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
          echo "ACTOR=${GITHUB_ACTOR@L}" >> "${GITHUB_ENV}"

      - name: 🐳 Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🛜 Build and push Docker image
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}

  deploy-to-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: 🐳 Set up Docker Buildx
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: 🔐 Login to Azure
        uses: Azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚢 Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: "DefaultResourceGroup-CQ"
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
